services:
  firefly-cardanoconnect:
    image: ghcr.io/blockfrost/firefly-cardanoconnect:docker-stuff
    build:
      context: ..
      target: firefly-cardanoconnect
    develop:
      watch:
      - action: rebuild
        path: ../firefly-cardanoconnect
    command: ./firefly-cardanoconnect --config-file ./config.yaml
    environment:
      - FIREFLY_CONNECTOR_BLOCKCHAIN_BLOCKFROST_KEY=${BLOCKFROST_KEY}
    ports:
      - 5018:5018
    volumes:
      - ./ipc:/ipc
      - connect-contracts:/contracts
      - connect-db:/db
      - ./connect.yaml:/app/config.yaml

  firefly-cardanosigner:
    image: ghcr.io/blockfrost/firefly-cardanosigner:docker-stuff
    build:
      context: ..
      target: firefly-cardanosigner
    develop:
      watch:
      - action: rebuild
        path: ../firefly-cardanosigner
    command: ./firefly-cardanosigner --config-file /app/config.yaml
    ports:
      - 8555:8555
    volumes:
      - ./wallet:/wallet
      - ./signer.yaml:/app/config.yaml

volumes:
  connect-contracts:
  connect-db:
