[package]
name = "firefly-cardanosigner"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/SundaeSwap-finance/firefly-cardano"

[dependencies]
aide = { version = "0.13", features = ["axum"] }
axum = "0.7"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
firefly-server = { path = "../firefly-server" }
schemars = "0.8"
serde = "1"
tokio = { version = "1", features = ["full"] }