[package]
name = "firefly-cardanosigner"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/SundaeSwap-finance/firefly-cardano"

[dependencies]
aide = { version = "0.13", features = ["axum"] }
axum = "0.7"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
firefly-server = { path = "../firefly-server" }
hex = "0.4"
minicbor = "0.25"
pallas-crypto = "0.31"
pallas-primitives = "0.31"
pallas-wallet = "0.31"
rand = "0.8"
schemars = "0.8"
serde = "1"
serde_json = "1"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }