[package]
name = "firefly-server"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/SundaeSwap-finance/firefly-cardano"

[dependencies]
aide = { version = "0.13", features = ["axum"] }
axum = "0.7"
axum-swagger-ui = "0.3"
anyhow = "1"
duration-str = "0.11"
figment = { version = "0.10", features = ["yaml", "env"] }
home = "0.5"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
schemars = "0.8"
serde = "1"
serde_json = "1"
tokio = "1"