[package]
name = "firefly-server"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/SundaeSwap-finance/firefly-cardano"

[dependencies]
aide = { version = "0.13", features = ["axum"] }
axum = "0.7"
axum-swagger-ui = "0.3"
anyhow = "1"
config = "0.14"
serde = "1"
tokio = "1"