[package]
name = "firefly-cardanoconnect"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/SundaeSwap-finance/firefly-cardano"

[dependencies]
aide = { version = "0.13", features = ["axum"] }
anyhow = "1"
axum = { version = "0.7", features = ["ws"] }
clap = { version = "4", features = ["derive"] }
pallas-codec = "0.30"
pallas-crypto = "0.30"
pallas-primitives = "0.30"
pallas-network = "0.30"
firefly-server = { path = "../firefly-server" }
hex = "0.4"
minicbor = "0.20"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
schemars = "0.8"
serde = "1"
tokio = { version = "1", features = ["full"] }
