[package]
name = "firefly-cardanoconnect"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/SundaeSwap-finance/firefly-cardano"

[dependencies]
aide = { version = "0.13", features = ["axum"] }
anyhow = "1"
axum = { version = "0.7", features = ["ws"] }
clap = { version = "4", features = ["derive"] }
firefly-server = { path = "../firefly-server" }
serde = "1"
tokio = { version = "1", features = ["full"] }